// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdwpbygbfhdmxsdghnem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkd3BieWdiZmhkbXhzZGdobmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODEzNTIsImV4cCI6MjA2Mzg1NzM1Mn0.ifgSgClW_H4iRc4HE8YQbHjV_Cy2VwkU5J3OCZedM0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);